// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCrf3a9UPnoV-ZMFLw1tAXIGGJLS_ZOfM',
    appId: '1:230311249767:web:7ef45f5545a75cfafa91c2',
    messagingSenderId: '230311249767',
    projectId: 'flutter-profile-firebase',
    authDomain: 'flutter-profile-firebase.firebaseapp.com',
    storageBucket: 'flutter-profile-firebase.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnexZfcxvmfbwtxNVSkwFGuPtMwFvN7AM',
    appId: '1:230311249767:android:c635b57822632466fa91c2',
    messagingSenderId: '230311249767',
    projectId: 'flutter-profile-firebase',
    storageBucket: 'flutter-profile-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCIcrR0rdAWVHPmAgcnhkm9tcIDG_pmpk',
    appId: '1:230311249767:ios:aadb56f37871391efa91c2',
    messagingSenderId: '230311249767',
    projectId: 'flutter-profile-firebase',
    storageBucket: 'flutter-profile-firebase.appspot.com',
    iosClientId: '230311249767-smun1n9nq0glo73uod7rfr3h0go7ap6a.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterProfileFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCIcrR0rdAWVHPmAgcnhkm9tcIDG_pmpk',
    appId: '1:230311249767:ios:aadb56f37871391efa91c2',
    messagingSenderId: '230311249767',
    projectId: 'flutter-profile-firebase',
    storageBucket: 'flutter-profile-firebase.appspot.com',
    iosClientId: '230311249767-smun1n9nq0glo73uod7rfr3h0go7ap6a.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterProfileFirebase',
  );
}
